resources:
  - secret.yaml
  - machinery.yaml
  - redis.yaml
  - rabbitMQ.yaml
  - postgresql-deployement.yaml
  - auth-service-deployment.yaml
  - user-service-deploy.yaml
  - video-service-deployment.yaml
  - websocket-service-deployment.yaml
  - thumbnail-maker-deployment.yaml
  - video-chunker-deployment.yaml
  - video-convertor.yaml
  - frontend.yaml
  # - traefik-cors-middleware.yaml
  # - middleware-sticky.yaml        # middleware before ingress
  - ingress.yaml
  # - sticky-ingress.yaml
