apiVersion: v1
kind: Secret
metadata:
  name: p2-secrets
  namespace: default
  labels:
    app: p2

type: Opaque
stringData:
  db_name: dbp2
  db_username: dev
  db_password: devpass
  db_root_password: root




  # github_username: Kitiphol
  # github_token: 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