apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: video-service
          image: ghcr.io/kitiphol/videoservice:latest@sha256:f0e6ebf622043978fd19740b03abfcc69e4025997050a682e9abfa7fa23e3f9b
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: p2-secret
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP