apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: websocket-service
          image: ghcr.io/kitiphol/websocketservice:latest@sha256:10b3f677ac551302aa6b33dc8001a1d0244c63f5f4385310a18ecbe3cba08398
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: p2-secret
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
