name: Build and Push Each Service

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u Kitiphol --password ${{ secrets.GH_PAT }}

      # Build & push Authentication
      - name: Build & push Authentication
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/Authentication
          push: true
          tags: ghcr.io/kitiphol/authentication:latest

      # Build & push UserService
      - name: Build & push UserService
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/UserService
          push: true
          tags: ghcr.io/kitiphol/userservice:latest

      # Build & push VideoService
      - name: Build & push VideoService
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/VideoService
          push: true
          tags: ghcr.io/kitiphol/videoservice:latest

      # Build & push WebsocketService
      - name: Build & push WebsocketService
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/WebsocketService
          push: true
          tags: ghcr.io/kitiphol/websocketservice:latest

      # Build & push VideoChunker
      - name: Build & push VideoChunker
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/VideoChunker
          push: true
          tags: ghcr.io/kitiphol/videochunker:latest

      # Build & push VideoConvertor
      - name: Build & push VideoConvertor
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/VideoConvertor
          push: true
          tags: ghcr.io/kitiphol/videoconvertor:latest

      # Build & push ThumbnailMaker
      - name: Build & push ThumbnailMaker
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/ThumbnailMaker
          push: true
          tags: ghcr.io/kitiphol/thumbnailmaker:latest

      # Build & push Frontend
      - name: Build & push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/toktik_frontend
          push: true
          tags: ghcr.io/kitiphol/toktik-frontend:latest